version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2020!"
    ports:
      - "15432:5432"
    networks:
      - postgres-network
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "limabrot879@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2020!"
    ports:
      - "16543:80"
    depends_on: 
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
